In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('adult.data', header=None,sep='\s+')
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K

In [5]:
df.columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status','occupation','relationship','race','sex',
              'capital-gain','capital-loss','hours-per-week:','native-country:', 'target']
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week:,native-country:,target
0,"39,","State-gov,","77516,","Bachelors,","13,","Never-married,","Adm-clerical,","Not-in-family,","White,","Male,","2174,","0,","40,","United-States,",<=50K
1,"50,","Self-emp-not-inc,","83311,","Bachelors,","13,","Married-civ-spouse,","Exec-managerial,","Husband,","White,","Male,","0,","0,","13,","United-States,",<=50K
2,"38,","Private,","215646,","HS-grad,","9,","Divorced,","Handlers-cleaners,","Not-in-family,","White,","Male,","0,","0,","40,","United-States,",<=50K
3,"53,","Private,","234721,","11th,","7,","Married-civ-spouse,","Handlers-cleaners,","Husband,","Black,","Male,","0,","0,","40,","United-States,",<=50K
4,"28,","Private,","338409,","Bachelors,","13,","Married-civ-spouse,","Prof-specialty,","Wife,","Black,","Female,","0,","0,","40,","Cuba,",<=50K

In [12]:
df.isnull().sum()

age                   0
workclass          1836
fnlwgt                0
education             0
education-num         0
marital-status        0
occupation            0
relationship          0
race                  0
sex                   0
capital-gain          0
capital-loss          0
hours-per-week:       0
native-country:       0
target                0
dtype: int64

In [9]:
df.workclass.value_counts()

workclass
Private,             22696
Self-emp-not-inc,     2541
Local-gov,            2093
?,                    1836
State-gov,            1298
Self-emp-inc,         1116
Federal-gov,           960
Without-pay,            14
Never-worked,            7
Name: count, dtype: int64

In [10]:
df.workclass = df.workclass.replace({'?,': np.nan})
df.workclass.isna().sum()

np.int64(1836)

In [11]:
df.describe()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week:,native-country:,target
count,32561,30725,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561,32561
unique,73,8,21648,16,16,7,15,6,5,2,119,92,94,42,2
top,"36,","Private,","164190,","HS-grad,","9,","Married-civ-spouse,","Prof-specialty,","Husband,","White,","Male,","0,","0,","40,","United-States,",<=50K
freq,898,22696,13,10501,10501,14976,4140,13193,27816,21790,29849,31042,15217,29170,24720

In [14]:
for i in df.columns:
    print(i, ':','\n', df[i].value_counts(),'\n')

age :
 age
36,    898
31,    888
34,    886
23,    877
35,    876
      ...
83,      6
88,      3
85,      3
86,      1
87,      1
Name: count, Length: 73, dtype: int64

workclass :
 workclass
Private,             22696
Self-emp-not-inc,     2541
Local-gov,            2093
State-gov,            1298
Self-emp-inc,         1116
Federal-gov,           960
Without-pay,            14
Never-worked,            7
Name: count, dtype: int64

fnlwgt :
 fnlwgt
164190,    13
203488,    13
123011,    13
148995,    12
121124,    12
           ..
232784,     1
325573,     1
140176,     1
318264,     1
257302,     1
Name: count, Length: 21648, dtype: int64

education :
 education
HS-grad,         10501
Some-college,     7291
Bachelors,        5355
Masters,          1723
Assoc-voc,        1382
11th,             1175
Assoc-acdm,       1067
10th,              933
7th-8th,           646
Prof-school,       576
9th,               514
12th,              433
Doctorate,         413
5th-6th,           333
1st-4th,           168
Preschool,          51
Name: count, dtype: int64

education-num :
 education-num
9,     10501
10,     7291
13,     5355
14,     1723
11,     1382
7,      1175
12,     1067
6,       933
4,       646
15,      576
5,       514
8,       433
16,      413
3,       333
2,       168
1,        51
Name: count, dtype: int64

marital-status :
 marital-status
Married-civ-spouse,       14976
Never-married,            10683
Divorced,                  4443
Separated,                 1025
Widowed,                    993
Married-spouse-absent,      418
Married-AF-spouse,           23
Name: count, dtype: int64

occupation :
 occupation
Prof-specialty,       4140
Craft-repair,         4099
Exec-managerial,      4066
Adm-clerical,         3770
Sales,                3650
Other-service,        3295
Machine-op-inspct,    2002
?,                    1843
Transport-moving,     1597
Handlers-cleaners,    1370
Farming-fishing,       994
Tech-support,          928
Protective-serv,       649
Priv-house-serv,       149
Armed-Forces,            9
Name: count, dtype: int64

relationship :
 relationship
Husband,           13193
Not-in-family,      8305
Own-child,          5068
Unmarried,          3446
Wife,               1568
Other-relative,      981
Name: count, dtype: int64

race :
 race
White,                 27816
Black,                  3124
Asian-Pac-Islander,     1039
Amer-Indian-Eskimo,      311
Other,                   271
Name: count, dtype: int64

sex :
 sex
Male,      21790
Female,    10771
Name: count, dtype: int64

capital-gain :
 capital-gain
0,        29849
15024,      347
7688,       284
7298,       246
99999,      159
          ...
1111,         1
2538,         1
22040,        1
4931,         1
5060,         1
Name: count, Length: 119, dtype: int64

capital-loss :
 capital-loss
0,       31042
1902,      202
1977,      168
1887,      159
1848,       51
         ...
2080,        1
1539,        1
1844,        1
2489,        1
1411,        1
Name: count, Length: 92, dtype: int64

hours-per-week: :
 hours-per-week:
40,    15217
50,     2819
45,     1824
60,     1475
35,     1297
       ...
82,        1
92,        1
87,        1
74,        1
94,        1
Name: count, Length: 94, dtype: int64

native-country: :
 native-country:
United-States,                 29170
Mexico,                          643
?,                               583
Philippines,                     198
Germany,                         137
Canada,                          121
Puerto-Rico,                     114
El-Salvador,                     106
India,                           100
Cuba,                             95
England,                          90
Jamaica,                          81
South,                            80
China,                            75
Italy,                            73
Dominican-Republic,               70
Vietnam,                          67
Guatemala,                        64
Japan,                            62
Poland,                           60
Columbia,                         59
Taiwan,                           51
Haiti,                            44
Iran,                             43
Portugal,                         37
Nicaragua,                        34
Peru,                             31
France,                           29
Greece,                           29
Ecuador,                          28
Ireland,                          24
Hong,                             20
Cambodia,                         19
Trinadad&Tobago,                  19
Laos,                             18
Thailand,                         18
Yugoslavia,                       16
Outlying-US(Guam-USVI-etc),       14
Honduras,                         13
Hungary,                          13
Scotland,                         12
Holand-Netherlands,                1
Name: count, dtype: int64

target :
 target
<=50K    24720
>50K      7841
Name: count, dtype: int64